import { z } from 'zod';
export type PoolId = 'main' | 'training';
export type AllocationType = 'public'|'reserved'|'lessons'|'club'|'unavailable'|'unknown'|'members-only'|'activity'|'recreational';
export type PoolConfiguration = 'Full 50m main pool'|'Split 25m main pool'|'Split 23m main pool'|'25m training pool'|'Mixed or restricted'|'Closed';
export interface Venue { id:string; name:string; address:string; sourceUrl:string }
export interface Pool { id:PoolId; name:string; length:number; maxLanes:number }
export interface PoolLane { number:number; allocation:AllocationType; label?:string }
export interface LaneAllocation { type:AllocationType; count:number; note?:string }
export interface Restriction { id:string; label:string; detail:string; severity:'low'|'medium'|'high' }
export interface SourceValidation { updatedAt?:string; confidence:'High'|'Medium'|'Low'; status:'verified'|'estimated'; note?:string }
export interface SwimBlock { id:string; date:string; start:string; end:string; pool:PoolId; configuration:PoolConfiguration; totalLanes:number|null; publicLanes:number|null; laneAllocations:LaneAllocation[]; restrictions:Restriction[]; originalSourceText:string; sourceUpdateTimestamp?:string; parsingConfidence:number; verified:boolean; expectedPressure:1|2|3|4|5; bestUse:string[]; source:SourceValidation }
export interface CrowdEstimate { pressure:1|2|3|4|5; label:string; basis:string }
export interface UserSwimPreference { goal:'fitness'|'technique'|'endurance'|'recovery'|'social'; duration:number; earliestStart:string; latestFinish:string; beforeWork:boolean; afterWork:boolean; format:'any'|'50m'|'25m'|'training'; crowdTolerance:1|2|3|4|5; homeLocation:string; timetableUrl:string }
export type JourneyMode='drive'|'walk'|'cycle'|'transit';
export interface SavedOrigin { id:string;label:string;type:'home'|'work'|'custom';addressLabel:string;latitude:number;longitude:number;createdAt:string;updatedAt:string }
export interface CurrentLocationOrigin { type:'current-location';latitude:number;longitude:number;accuracyMetres:number|null;capturedAt:string }
export type JourneyOrigin=SavedOrigin|CurrentLocationOrigin;
export interface JourneyRequest { origin:JourneyOrigin;destinationVenueId:string;departureTime:string;mode:JourneyMode }
export interface JourneyEstimate { id:string;originLabel:string;destinationVenueId:string;mode:JourneyMode;requestedDepartureTime:string;estimatedDurationMinutes:number;staticDurationMinutes:number|null;trafficDelayMinutes:number|null;distanceMetres:number|null;routeSummary:string|null;provider:'google-routes'|'mock'|'fallback';trafficModel:string|null;fetchedAt:string;expiresAt:string;confidence:'high'|'medium'|'low';warnings:string[];cached?:boolean }
export interface ArrivalPlan { sessionId:string;sessionStartTime:string;intendedWaterEntryTime:string;journeyDurationMinutes:number;journeyUncertaintyBufferMinutes:number;parkingBufferMinutes:number;changingBufferMinutes:number;totalPreSwimBufferMinutes:number;leaveByTime:string;expectedArrivalTime:string;status:'comfortable'|'tight'|'late'|'unknown';reasons:string[] }
export interface SessionFeasibility { plannedArrivalTime:string;possibleWaterEntryTime:string;sessionEndTime:string;availableSwimMinutes:number;meetsMinimumUsefulDuration:boolean;status:'comfortable'|'workable'|'not-worth-travelling'|'missed' }
export interface JourneyPreferences { defaultOriginId:string|null;defaultMode:JourneyMode;parkingBufferMinutes:number;changingBufferMinutes:number;journeyUncertaintyBufferMinutes:number;minimumUsefulSwimMinutes:number;maximumPreferredJourneyMinutes:number|null;allowCurrentLocation:boolean;mockScenario:'clear'|'moderate'|'heavy'|'unavailable'|'timeout'|'quota' }
export interface Recommendation { block:SwimBlock; score:number; colour:'green'|'amber'|'red'; experience:'Excellent'|'Good'|'Acceptable'|'Poor'; confidence:'High'|'Medium'|'Low'; reasonCodes:string[]; explanation:string }
export interface PostSwimFeedback { id:string; createdAt:string; crowding:number; enjoyment:number; trainingQuality:number; chooseAgain:boolean; note?:string; pool:PoolId; sessionId:string }
export const feedbackSchema=z.object({crowding:z.number().min(1).max(5),enjoyment:z.number().min(1).max(5),trainingQuality:z.number().min(1).max(5),chooseAgain:z.boolean(),note:z.string().max(500).optional(),pool:z.enum(['main','training']),sessionId:z.string()});
export const defaultPreferences:UserSwimPreference={goal:'fitness',duration:45,earliestStart:'06:00',latestFinish:'21:30',beforeWork:true,afterWork:true,format:'any',crowdTolerance:3,homeLocation:'Swansea (set your area)',timetableUrl:'https://www.walesnationalpoolswansea.co.uk/'};
export const defaultJourneyPreferences:JourneyPreferences={defaultOriginId:null,defaultMode:'drive',parkingBufferMinutes:7,changingBufferMinutes:10,journeyUncertaintyBufferMinutes:5,minimumUsefulSwimMinutes:30,maximumPreferredJourneyMinutes:30,allowCurrentLocation:true,mockScenario:'moderate'};
export const savedOriginSchema=z.object({id:z.string(),label:z.string().min(1).max(80),type:z.enum(['home','work','custom']),addressLabel:z.string().max(160),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180),createdAt:z.string(),updatedAt:z.string()});
export type CrowdObservation='lane-to-myself'|'comfortable-sharing'|'frequent-overtaking'|'pace-mismatch'|'waiting-at-wall'|'lesson-congestion'|'club-congestion'|'poor-lane-etiquette'|'good-lane-etiquette'|'changing-room-busy'|'parking-busy'|'unexpected-restriction'|'configuration-different'|'other';
export interface SwimExperienceReport {id:string;userId:string|null;venueId:string;sessionId:string|null;timetableSnapshotId:string|null;swimDate:string;scheduledStartTime:string|null;scheduledEndTime:string|null;actualArrivalTime:string|null;actualWaterEntryTime:string|null;actualFinishTime:string|null;poolId:string;configuration:'main-50m'|'main-25m'|'main-23m'|'training-25m'|'mixed'|'recreational'|'unknown';publicLaneCount:number|null;knownRestrictions:string[];intendedGoal:'technique'|'endurance'|'pacing'|'easy'|'drills'|'fins-paddles'|'general';actualCrowding:1|2|3|4|5;enjoyment:1|2|3|4|5;trainingQuality:1|2|3|4|5;wouldChooseAgain:boolean;attended:boolean;crowdNotes:CrowdObservation[];freeTextNote:string|null;recommendationShown:boolean;recommendationScoreAtDecision:number|null;recommendationColourAtDecision:'green'|'amber'|'red'|null;predictedPressureAtDecision:'low'|'moderate'|'high'|'very-high'|null;journeyEstimateMinutes:number|null;typicality:'typical'|'unusual'|'uncertain';unusualReason:'event'|'closure'|'unexpected-restriction'|'holiday'|'weather'|'configuration-change'|'unknown'|null;createdAt:string;updatedAt:string}
export interface AttendanceOutcome {recommendationId:string|null;sessionId:string|null;outcome:'attended'|'chose-alternative'|'planned-but-skipped'|'not-considered';skipReason:'traffic'|'too-tired'|'too-early'|'too-late'|'crowding-concern'|'short-window'|'schedule-conflict'|'weather'|'changed-mind'|'other'|null;alternativeSessionId:string|null;recordedAt:string}
export interface CrowdPrediction {venueId:string;poolId:string;date:string;startTime:string;endTime:string;predictedPressure:'low'|'moderate'|'high'|'very-high';confidence:'high'|'medium'|'low';evidenceCount:number;recentEvidenceCount:number;baselineScore:number;historicalAdjustment:number;capacityAdjustment:number;exceptionAdjustment:number;reasons:string[];evidenceSummary:string[];lastEvidenceAt:string|null}
export interface PersonalSlotPreference {venueId:string;poolId:string;weekday:number;timeBucket:string;goal:string;affinity:'strong-positive'|'positive'|'neutral'|'negative'|'strong-negative';attendanceRate:number|null;enjoymentScore:number|null;trainingQualityScore:number|null;chooseAgainRate:number|null;evidenceCount:number;confidence:'high'|'medium'|'low';reasons:string[]}
export const experienceReportSchema=z.object({id:z.string(),userId:z.string().nullable(),venueId:z.string(),sessionId:z.string().nullable(),timetableSnapshotId:z.string().nullable(),swimDate:z.string(),scheduledStartTime:z.string().nullable(),scheduledEndTime:z.string().nullable(),actualArrivalTime:z.string().nullable(),actualWaterEntryTime:z.string().nullable(),actualFinishTime:z.string().nullable(),poolId:z.string(),configuration:z.enum(['main-50m','main-25m','main-23m','training-25m','mixed','recreational','unknown']),publicLaneCount:z.number().nullable(),knownRestrictions:z.array(z.string()),intendedGoal:z.enum(['technique','endurance','pacing','easy','drills','fins-paddles','general']),actualCrowding:z.number().int().min(1).max(5),enjoyment:z.number().int().min(1).max(5),trainingQuality:z.number().int().min(1).max(5),wouldChooseAgain:z.boolean(),attended:z.boolean(),crowdNotes:z.array(z.string()),freeTextNote:z.string().nullable(),recommendationShown:z.boolean(),recommendationScoreAtDecision:z.number().nullable(),recommendationColourAtDecision:z.enum(['green','amber','red']).nullable(),predictedPressureAtDecision:z.enum(['low','moderate','high','very-high']).nullable(),journeyEstimateMinutes:z.number().nullable(),typicality:z.enum(['typical','unusual','uncertain']),unusualReason:z.enum(['event','closure','unexpected-restriction','holiday','weather','configuration-change','unknown']).nullable(),createdAt:z.string(),updatedAt:z.string()});
