import * as cheerio from 'cheerio'; import { addDays, format, isValid, parse } from 'date-fns'; import type { ExtractionResult, RawSourceSnapshot, TimetableCoverage, ValidationIssue } from './types'; import { normaliseWeekday, parseTimeRange } from './normalise';
const issue=(code:string,message:string,severity:ValidationIssue['severity']='warning'):ValidationIssue=>({id:`${code}-${Math.random().toString(36).slice(2,8)}`,code,message,severity});
const cancelled=(el:cheerio.Cheerio<any>,text:string)=>el.is('del,s')||el.find('del,s,[style*="line-through" i],.cancelled,.canceled').length>0||/\b(cancelled|cancellation|unavailable|closed|no public swimming|competition)\b/i.test(text);
const dateFromText=(text:string)=>{const withYear=text.match(/(?:monday|tuesday|wednesday|thursday|friday|saturday|sunday)?\s*(\d{1,2}(?:st|nd|rd|th)?\s+(?:jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:tember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)(?:\s+\d{4})?)/i);if(!withYear)return null;let s=withYear[1].replace(/(st|nd|rd|th)/,'');if(!/\d{4}/.test(s))s+=` ${new Date().getFullYear()}`;const d=parse(s,'d MMMM yyyy',new Date());return isValid(d)?format(d,'yyyy-MM-dd'):null};
export function coverageFromText(text:string):TimetableCoverage{const dated=[...text.matchAll(/(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\s+(\d{1,2}(?:st|nd|rd|th)?\s+\w+(?:\s+\d{4})?)/gi)].map(m=>({day:m[1].toLowerCase(),date:dateFromText(m[0])})).filter(x=>x.date);const monday=dated.find(x=>x.day==='monday')?.date||null;return {monday,sunday:monday?format(addDays(new Date(`${monday}T12:00:00Z`),6),'yyyy-MM-dd'):null,displayedDateText:dated[0]?text.match(/(?:Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\s+\d{1,2}[^\n]*/i)?.[0]||null:null,confidence:dated.length>=2?'high':monday?'medium':'low',derivation:dated.length?['Derived from explicit weekday/date headings.']:['No complete Monday date heading found.']}}
export function extractSnapshot(snapshot:RawSourceSnapshot):ExtractionResult{const $=cheerio.load(snapshot.html);const body=$('body').text().replace(/\u00a0/g,' ');const coverage=coverageFromText(body);const issues:ValidationIssue[]=[];const update=body.match(/updated\s+(\d{1,2}[/.]\d{1,2}[/.]\d{4}\s+\d{1,2}:\d{2}|\w+\s+\d{4})/i);if(!update)issues.push(issue('UPDATE_TIMESTAMP_MISSING','The official page did not state when this timetable was updated.'));if(!coverage.monday)issues.push(issue('COVERAGE_MISSING','A precise Monday-to-Sunday timetable period could not be established.','blocking'));
 let day:string|null=null,dayDate:string|null=null,order=0;const rows:ExtractionResult['rows']=[],notices:ExtractionResult['notices']=[],unparsed:ExtractionResult['unparsed']=[];const elements=$('h1,h2,h3,h4,p,li,tr,div').toArray();for(const node of elements){const el=$(node),text=el.text().replace(/\s+/g,' ').trim();if(!text||text.length>900)continue;const weekday=text.match(/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)\b/i);if(weekday){day=normaliseWeekday(weekday[1]);dayDate=dateFromText(text);if(/closed|competition|gala/i.test(text))notices.push({id:`notice-${order}`,type:/competition|gala/i.test(text)?'competition':'venue-closure',evidence:text,severity:'warning',confidence:'medium'});}
 const range=parseTimeRange(text);if(range&&day){const rawPoolText=(text.match(/(Training Pool|50m Pool|25m Split|23m Split|National Pool|Main Pool)/i)||[])[0]||null;const isCancelled=cancelled(el,text);rows.push({id:`row-${snapshot.id}-${order++}`,sourceSnapshotId:snapshot.id,dayText:day,displayedDateText:dayDate,rawTimeText:range.raw,rawPoolText,rawSessionText:text,rawRestrictionText:/members only|lesson|club|aqua jogging|fins|closed|competition/i.test(text)?text:null,isStruckThrough:el.is('del,s')||el.find('del,s,[style*="line-through" i]').length>0,isCancelled,htmlContext:$.html(el).replace(/<script[\s\S]*?<\/script>/gi,''),sourceOrder:order,extractionWarnings:[]});}else if(day&&/lane|pool|swim|closed|competition/i.test(text)&&text.length<280)unparsed.push({text,context:day,reason:'Timetable-like text had no recognised time range.',suggestedAction:'Review the source row and add a correction if it represents a session.'});}
 if(rows.length===0)issues.push(issue('NO_ROWS_EXTRACTED','No timed timetable rows could be extracted from the source page.','blocking'));const days=new Set(rows.map(r=>r.dayText));if(days.size<7)issues.push(issue('MISSING_DAYS','One or more days have no structured session rows.','warning'));return {snapshot,coverage,rows,notices,unparsed,issues,structure:{headings:$('h1,h2,h3,h4').length,daySections:days.size,extractedRows:rows.length,interpretedTextRatio:rows.length?Math.min(1,rows.length/(rows.length+unparsed.length)):0}}
}
