import { z } from 'zod'; import type { SwimBlock, Venue } from '../lib/models';
export type Severity='info'|'warning'|'error'|'blocking'; export interface ValidationIssue { id:string; severity:Severity; code:string; message:string; sourceRowId?:string; sessionId?:string; evidence?:string; suggestedAction?:string }
export interface RawSourceSnapshot { id:string; sourceId:string; requestedUrl:string; finalUrl:string; httpStatus:number; fetchedAt:string; headers:Record<string,string>; html:string; contentHash:string; archive?:{htmlFilename:string;metadataFilename:string} }
export interface TimetableCoverage { monday:string|null; sunday:string|null; displayedDateText:string|null; confidence:'high'|'medium'|'low'; derivation:string[] }
export interface ExtractedTimetableRow { id:string; sourceSnapshotId:string; dayText:string|null; displayedDateText:string|null; rawTimeText:string|null; rawPoolText:string|null; rawSessionText:string; rawRestrictionText:string|null; isStruckThrough:boolean; isCancelled:boolean; htmlContext?:string; sourceOrder:number; extractionWarnings:ValidationIssue[] }
export interface ExceptionalNotice { id:string; type:'venue-closure'|'main-pool-closure'|'training-pool-closure'|'competition'|'gala'|'maintenance'|'altered-hours'|'reduced-lanes'|'unknown'; start?:string; end?:string; pool?:'main'|'training'; evidence:string; severity:Severity; confidence:'high'|'medium'|'low' }
export interface InterpretedSession extends SwimBlock { sourceSnapshotId:string; sourceRowId:string; reservedLanes:number|null; sessionLabels:string[]; reasonCodes:string[]; warnings:ValidationIssue[]; publishable:boolean; }
export interface ExtractionResult { snapshot:RawSourceSnapshot; coverage:TimetableCoverage; rows:ExtractedTimetableRow[]; notices:ExceptionalNotice[]; unparsed:Array<{text:string;context:string;reason:string;suggestedAction:string}>; issues:ValidationIssue[]; structure:{headings:number;daySections:number;extractedRows:number;interpretedTextRatio:number} }
export interface TimetableChange { type:'added'|'removed'|'modified'|'cancelled'|'structural'; key:string; message:string; before?:Partial<InterpretedSession>; after?:Partial<InterpretedSession> }
export interface TimetableDiff { previousSnapshotId:string|null;currentSnapshotId:string;changes:TimetableChange[];summary:{added:number;removed:number;modified:number;cancelled:number} }
export interface ReviewOverlay { snapshotId:string;reviewedAt:string;reviewer:string;status:'pending'|'approved'|'rejected';rowCorrections:Array<{sourceRowId:string;fieldChanges:Record<string,unknown>;note:string}>;addedSessions:InterpretedSession[];removedSessionIds:string[];approvalNote?:string }
export type FreshnessStatus='current-verified'|'current-partial'|'pending-review'|'stale-previous'|'source-unavailable'|'no-timetable';
export interface PublishedTimetable { venue:Venue;coverage:TimetableCoverage;source:{sourceId:string;url:string;finalUrl?:string;fetchedAt?:string;updateTimestamp:string|null;contentHash?:string;manualReview:'none'|'pending'|'approved';warnings:number};publishedAt:string;freshness:FreshnessStatus;sessions:InterpretedSession[];closures:ExceptionalNotice[];validationSummary:{issues:ValidationIssue[];blocking:boolean};diff?:TimetableDiff;manualReviewRequired:boolean }
export const publishedTimetableSchema=z.object({venue:z.object({id:z.string(),name:z.string(),address:z.string(),sourceUrl:z.string()}),coverage:z.object({monday:z.string().nullable(),sunday:z.string().nullable(),displayedDateText:z.string().nullable(),confidence:z.enum(['high','medium','low']),derivation:z.array(z.string())}),source:z.object({sourceId:z.string(),url:z.string(),finalUrl:z.string().optional(),fetchedAt:z.string().optional(),updateTimestamp:z.string().nullable(),contentHash:z.string().optional(),manualReview:z.enum(['none','pending','approved']),warnings:z.number()}),publishedAt:z.string(),freshness:z.enum(['current-verified','current-partial','pending-review','stale-previous','source-unavailable','no-timetable']),sessions:z.array(z.any()),closures:z.array(z.any()),validationSummary:z.object({issues:z.array(z.any()),blocking:z.boolean()}),manualReviewRequired:z.boolean()}); export interface TimetableSourceAdapter { sourceId:string;fetchSource():Promise<RawSourceSnapshot> }
